name: Auto Release

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  release:
    if: github.event.pull_request.merged == true && github.event.pull_request.head.ref == 'dev'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Dar permisos de ejecución a gradlew
        run: chmod +x gradlew

      - name: Build con Gradle
        run: ./gradlew build --no-daemon

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "v${{ github.run_number }}"
          name: "Release v${{ github.run_number }} (PR #${{ github.event.pull_request.number }})"
          generate_release_notes: true
          files: |
            build/libs/*.jar